### PR TITLE
add namespaces to default search namespaces

### PR DESCRIPTION
**Pull request by ghost**
added user, project, conservapedia, and fun to namespaces to be searched by default

### CODE REVIEW

**Comment by tstarling** [comment]
Was there any discussion about this on-wiki? It's a bit unconventional.

**Comment by ghost** [comment]
no on-wiki discussion. iirc search pre-update returned results from *all* namespaces. my thoughts:

* conservapedia and fun: they're basically alternativ &, less-used mainspaces
* project: because a lot of "policy" articles have weird titles
* user: because [a] finding users [b] userspace pages

i was also unclear if this controls the "search suggestions" or just the search page -- if "search suggestions" changed, then this is terrible idea

do you suggest on-wiki discussion?

**Comment by tstarling** [comment]
The main issue is that $wgNamespacesToBeSearchedDefault affects anonymous users, particularly readers, so the usual theory is that it should only search the content namespaces. No WMF wiki has the User namespace in the default search, in fact many of them use $wgNamespaceRobotPolicies to exclude the User namespace from Google as well, since the User namespace has a lot of material which doesn't adhere to the wiki's policies.

When you click the "advanced" tab in [[Special:Search]], there is a namespace list and a checkbox "Remember selection for future searches". It's assumed that editors who need to regularly search the user namespace will use that feature.

The reason I'm suggesting on-wiki discussion is because it's kind of awkward for me to act as a gatekeeper. You're a Board member, and I hardly know this community. If you made your proposal on wiki then hopefully someone else would point out these issues, so that I wouldn't have to. If you want to go ahead with the change after considering the issues, then that is fine with me.

**Comment by ghost** [comment]
That's all fair -- thanks for letting me know.

**Comment by ghost** [comment]
seems unnecessary -- and would require a switch for russionalwiki. closed

**Pull request closed without merging**
