### PR TITLE
Add "RW" and "RW_talk" namespace aliases

### PR DESCRIPTION
**Pull request by Christopher36**
Add "RW" as a namespace alias for "RationalWiki", see tech support. I only found out about the existence of php a week ago so I've probably done something wrong.

### CODE REVIEW

**Comment by Christopher36** [comment]
I think I've done something wrong.

**Comment by ghost** [comment]
Seems fine to me, though I'd bet very few people will type "RW_talk" into the search bar.

**Comment by Christopher36** [comment]
Wikipedia has it, might as well.

**Comment by tstarling** [comment]
It's fine, but namespaceDupes.php needs to be run on the wiki immediately after the change is merged, otherwise all these redirects will become inaccessible:

http://rationalwiki.org/w/index.php?title=Special%3APrefixIndex&prefix=RW%3A&namespace=0

Running namespaceDupes.php may produce conflicts, which then need to be cleaned up manually, usually by deleting redundant redirects.

**Comment by ghost** [comment]
Gotcha. @Tim, is running namespaceDupes.php something you can do, or would
you prefer that one of us runs it?

**Comment by tstarling** [comment]
I can run it.

**Pull request merged**
